import: definition.yaml

concurrency:
  task:
    # cg-std: 8
    # dbbench-std: 3
    # os-std: 6
    # kg-std: 10
    # ltp-std: 10
    # alfworld-std: 5
    # m2w-std: 2
    webshop-std: 10
    # ltp-dev: 1
  agent:
    8bins: 10

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - 8bins
    task:
      # - dbbench-std
      # - os-std
      # - kg-std
      # - cg-std
      # - ltp-std
      # - alfworld-std
      # - m2w-std
      # - ltp-dev
      - webshop-std
output: "outputs/{TIMESTAMP}"