definition:
  import: tasks/task_assembly.yaml

start:
  # cg-std: 8
  # dbbench-std: 3
  # os-std: 6
  # kg-std: 10
  # ltp-std: 10
  # alfworld-std: 5
  # m2w-std: 2 
  # ltp-dev: 10
  webshop-std: 10